# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03787d83795c1aea2521a0299511e380baddd9fd61c1bdf0fd5656a1c36fe0e5f3ff41ccfdb3b681d2af2d20863c2993fb3037012218940d2d02140a842f7bc0

test:
  secret_key_base: dbdf8bed9143a8121a09e37c8371184da89021f59fef69bd1d0aca5c70de5fef98c431f14e1a7694611e0575b1b97596f7682557599599dcc77b726b40a0a763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
